//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryAjaxModal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Job
    {
        public short ID { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [Display(Name= "Tên công việc")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "Mức lương")]
        public decimal Salary { get; set; }
        [Display(Name = "Ngày tạo")]
        [DataType(DataType.DateTime), Required(ErrorMessage = "This field is required.")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm}", ApplyFormatInEditMode = true)]
        public System.DateTime Datecreated { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "Kích hoạt")]
        public bool Activated { get; set; }
    }
}
