//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryAjaxModal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobEmployee
    {
        public int ID { get; set; }
        public string Empid { get; set; }
        public Nullable<short> Jobid { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Job Job { get; set; }
    }
}
